=== balena-io-modules/balena-compose/lib/parse/schemas/config_schema_v2.4.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "config_schema_v2.4.json",
  "type": "object",

  "properties": {
    "version": {
      "type": "string"
    },

    "services": {
      "id": "#/properties/services",
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9._-]+$": {
          "$ref": "#/definitions/service"
        }
      },
      "additionalProperties": false
    },

    "networks": {
      "id": "#/properties/networks",
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9._-]+$": {
          "$ref": "#/definitions/network"
        }
      }
    },

    "volumes": {
      "id": "#/properties/volumes",
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9._-]+$": {
          "$ref": "#/definitions/volume"
        }
      },
      "additionalProperties": false
    }
  },

  "patternProperties": {"^x-": {}},
  "additionalProperties": false,

  "definitions": {

    "service": {
      "id": "#/definitions/service",
      "type": "object",

      "properties": {
        "blkio_config": {
          "type": "object",
          "properties": {
            "device_read_bps": {
              "type": "array",
              "items": {"$ref": "#/definitions/blkio_limit"}
            },
            "device_read_iops": {
              "type": "array",
              "items": {"$ref": "#/definitions/blkio_limit"}
            },
            "device_write_bps": {
              "type": "array",
              "items": {"$ref": "#/definitions/blkio_limit"}
            },
            "device_write_iops": {
              "type": "array",
              "items": {"$ref": "#/definitions/blkio_limit"}
            },
            "weight": {"type": "integer"},
            "weight_device": {
              "type": "array",
              "items": {"$ref": "#/definitions/blkio_weight"}
            }
          },
          "additionalProperties": false
        },

        "build": {
          "oneOf": [
            {"type": "string"},
            {
              "type": "object",
              "properties": {
                "args": {"$ref": "#/definitions/list_or_dict"},
                "cache_from": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
                "context": {"type": "string"},
                "dockerfile": {"type": "string"},
                "extra_hosts": {"$ref": "#/definitions/list_or_dict"},
                "host": {"type": "string"},
                "isolation": {"type": "string"},
                "labels": {"$ref": "#/definitions/list_or_dict"},
                "network": {"type": "string"},
                "shm_size": {"type": ["number", "string"]},
                "target": {"type": "string"}
              },
              "additionalProperties": false
            }
          ]
        },
        "cap_add": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
        "cap_drop": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
        "cgroup_parent": {"type": "string"},
        "command": {
          "oneOf": [
            {"type": "string"},
            {"type": "array", "items": {"type": "string"}}
          ]
        },
        "container_name": {"type": "string"},
        "cpu_shares": {"type": ["number", "string"]},
        "cpu_quota": {"type": ["number", "string"]},
        "cpu_rt_runtime": {"type": ["number", "string"]},
        "cpu_rt_period": {"type": ["number", "string"]},
        "cpuset": {"type": "string"},
        "depends_on": {
          "oneOf": [
            {"$ref": "#/definitions/list_of_strings"},
            {
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "^[a-zA-Z0-9._-]+$": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "condition": {
                      "type": "string",
                      "enum": ["service_started", "service_healthy"]
                    }
                  },
                  "required": ["condition"]
                }
              }
            }
          ]
        },
        "devices": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
        "device_cgroup_rules": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
        "dns_opt": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "dns": {"$ref": "#/definitions/string_or_list"},
        "dns_search": {"$ref": "#/definitions/string_or_list"},
        "domainname": {"type": "string"},
        "entrypoint": {
          "oneOf": [
            {"type": "string"},
            {"type": "array", "items": {"type": "string"}}
          ]
        },
        "env_file": {"$ref": "#/definitions/string_or_list"},
        "environment": {"$ref": "#/definitions/list_or_dict"},

        "expose": {
          "type": "array",
          "items": {
            "type": ["string", "number"],
            "format": "expose"
          },
          "uniqueItems": true
        },

        "extends": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "object",

              "properties": {
                "service": {"type": "string"},
                "file": {"type": "string"}
              },
              "required": ["service"],
              "additionalProperties": false
            }
          ]
        },

        "external_links": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
        "extra_hosts": {"$ref": "#/definitions/list_or_dict"},
        "healthcheck": {"$ref": "#/definitions/healthcheck"},
        "hostname": {"type": "string"},
        "image": {"type": "string"},
        "init": {"type": "boolean"},
        "ipc": {"type": "string"},
        "isolation": {"type": "string"},
        "labels": {"$ref": "#/definitions/list_or_dict"},
        "links": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},

        "logging": {
            "type": "object",

            "properties": {
                "driver": {"type": "string"},
                "options": {"type": "object"}
            },
            "additionalProperties": false
        },

        "mac_address": {"type": "string"},
        "mem_limit": {"type": ["number", "string"]},
        "mem_reservation": {"type": ["string", "integer"]},
        "mem_swappiness": {"type": "integer"},
        "memswap_limit": {"type": ["number", "string"]},
        "network_mode": {"type": "string"},

        "networks": {
          "oneOf": [
            {"$ref": "#/definitions/list_of_strings"},
            {
              "type": "object",
              "patternProperties": {
                "^[a-zA-Z0-9._-]+$": {
                  "oneOf": [
                    {
                      "type": "object",
                      "properties": {
                        "aliases": {"$ref": "#/definitions/list_of_strings"},
                        "ipv4_address": {"type": "string"},
                        "ipv6_address": {"type": "string"},
                        "link_local_ips": {"$ref": "#/definitions/list_of_strings"}
                      },
                      "additionalProperties": false
                    },
                    {"type": "null"}
                  ]
                }
              },
              "additionalProperties": false
            }
          ]
        },
        "oom_kill_disable": {"type": "boolean"},
        "oom_score_adj": {"type": "integer", "minimum": -1000, "maximum": 1000},
        "group_add": {
            "type": "array",
            "items": {
                "type": ["string", "number"]
            },
            "uniqueItems": true
        },
        "pid": {"type": ["string", "null"]},

        "ports": {
          "type": "array",
          "items": {
            "type": ["string", "number"],
            "format": "ports"
          },
          "uniqueItems": true
        },

        "privileged": {"type": "boolean"},
        "read_only": {"type": "boolean"},
        "restart": {"type": "string"},
        "runtime": {"type": "string"},
        "scale": {"type": "number"},
        "security_opt": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
        "shm_size": {"type": ["number", "string"]},
        "sysctls": {"$ref": "#/definitions/list_or_dict"},
        "pids_limit": {"type": ["number", "string"]},
        "platform": {"type": "string"},
        "stdin_open": {"type": "boolean"},
        "stop_grace_period": {"type": "string", "format": "duration"},
        "stop_signal": {"type": "string"},
        "storage_opt": {"type": "object"},
        "tmpfs": {"$ref": "#/definitions/string_or_list"},
        "tty": {"type": "boolean"},
        "ulimits": {
          "type": "object",
          "patternProperties": {
            "^[a-z]+$": {
              "oneOf": [
                {"type": "integer"},
                {
                  "type":"object",
                  "properties": {
                    "hard": {"type": "integer"},
                    "soft": {"type": "integer"}
                  },
                  "required": ["soft", "hard"],
                  "additionalProperties": false
                }
              ]
            }
          }
        },
        "user": {"type": "string"},
        "userns_mode": {"type": "string"},
        "volumes": {"$ref": "#/definitions/volumes"},
        "volume_driver": {"type": "string"},
        "volumes_from": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
        "working_dir": {"type": "string"},
        "profiles": {"type": "array", "items": {"type": "string"}, "uniqueItems": true}
      },

      "dependencies": {
        "memswap_limit": ["mem_limit"]
      },
      "patternProperties": {"^x-": {}},
      "additionalProperties": false
    },

    "healthcheck": {
      "id": "#/definitions/healthcheck",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "disable": {"type": "boolean"},
        "interval": {"type": "string"},
        "retries": {"type": "number"},
        "start_period": {"type": "string"},
        "test": {
          "oneOf": [
            {"type": "string"},
            {"type": "array", "items": {"type": "string"}}
          ]
        },
        "timeout": {"type": "string"}
      }
    },

    "network": {
      "id": "#/definitions/network",
      "type": "object",
      "properties": {
        "driver": {"type": "string"},
        "driver_opts": {
          "type": "object",
          "patternProperties": {
            "^.+$": {"type": ["string", "number"]}
          }
        },
        "ipam": {
            "type": "object",
            "properties": {
                "driver": {"type": "string"},
                "config": {
                    "type": "array"
                },
                "options": {
                  "type": "object",
                  "patternProperties": {
                    "^.+$": {"type": "string"}
                  },
                  "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "external": {
          "type": ["boolean", "object"],
          "properties": {
            "name": {"type": "string"}
          },
          "additionalProperties": false
        },
        "internal": {"type": "boolean"},
        "enable_ipv6": {"type": "boolean"},
        "labels": {"$ref": "#/definitions/list_or_dict"}
      },
      "patternProperties": {"^x-": {}},
      "additionalProperties": false
    },

    "volume": {
      "id": "#/definitions/volume",
      "type": ["object", "null"],
      "properties": {
        "driver": {"type": "string"},
        "driver_opts": {
          "type": "object",
          "patternProperties": {
            "^.+$": {"type": ["string", "number"]}
          }
        },
        "external": {
          "type": ["boolean", "object"],
          "properties": {
            "name": {"type": "string"}
          },
          "additionalProperties": false
        },
        "labels": {"$ref": "#/definitions/list_or_dict"},
        "name": {"type": "string"}
      },
      "patternProperties": {"^x-": {}},
      "additionalProperties": false
    },

    "volumes": {
      "id": "#/definitions/volumes",
      "type": "array",
      "items": {
        "oneOf": [
          {"type": "string"},
          {
            "type": "object",
            "required": ["type"],
            "properties": {
              "type": {"type": "string"},
              "source": {"type": "string"},
              "target": {"type": "string"},
              "read_only": {"type": "boolean"},
              "bind": {
                "type": "object",
                "properties": {
                  "propagation": {"type": "string"}
                },
                "additionalProperties": false
              },
              "volume": {
                "type": "object",
                "properties": {
                  "nocopy": {"type": "boolean"}
                },
                "additionalProperties": false
              },
              "tmpfs": {
                "type": "object",
                "properties": {
                  "size": {
                    "type": "integer",
                    "minimum": 0
                  }
                },
                "additionalProperties": false
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "uniqueItems": true
    },

    "string_or_list": {
      "oneOf": [
        {"type": "string"},
        {"$ref": "#/definitions/list_of_strings"}
      ]
    },

    "list_of_strings": {
      "type": "array",
      "items": {"type": "string"},
      "uniqueItems": true
    },

    "list_or_dict": {
      "oneOf": [
        {
          "type": "object",
          "patternProperties": {
            ".+": {
              "type": ["string", "number", "null"]
            }
          },
          "additionalProperties": false
        },
        {"type": "array", "items": {"type": "string"}, "uniqueItems": true}
      ]
    },

    "blkio_limit": {
      "type": "object",
      "properties": {
        "path": {"type": "string"},
        "rate": {"type": ["integer", "string"]}
      },
      "additionalProperties": false
    },
    "blkio_weight": {
      "type": "object",
      "properties": {
        "path": {"type": "string"},
        "weight": {"type": "integer"}
      },
      "additionalProperties": false
    },

    "constraints": {
      "service": {
        "id": "#/definitions/constraints/service",
        "anyOf": [
          {"required": ["build"]},
          {"required": ["image"]}
        ],
        "properties": {
          "build": {
            "required": ["context"]
          }
        }
      }
    }
  }
}

=== balena-io-modules/balena-compose/test/parse/fixtures/default.json
{
  "version": "2.4",
  "networks": {
    "n1": {},
    "n2": null
  },
  "volumes": {
    "v1": {},
    "v2": null
  },
  "services": {
    "s1": {
      "build": "./s1",
      "ports": [
        "80:5000"
      ],
      "depends_on": {
        "s3": {
          "condition": "service_started"
        }
      },
      "environment": [
        "SOME_VAR=some=value"
      ],
      "env_file": "./relative/parent1/parent2/parent3/../../twoupwards.env"
    },
    "s2": {
      "build": {
        "context": "./s2",
        "target": "stage1",
        "network": "none"
      },
      "depends_on": [
        "s1",
        "s3"
      ],
      "privileged": true,
      "environment": {
        "SOME_VAR": "some value"
      },
      "env_file": [
        "./relative/parent1/parent2/parent3/../../twoupwards.env",
        "./relative/parent1/twoupwards.env",
        "./foo/bar/env.env"
      ],
      "extra_hosts": {
        "foo": "127.0.0.1"
      },
      "volumes": [
        "v2:/v2:ro"
      ]
    },
    "s3": {
      "image": "some/image",
      "ports": [
        1000,
        "1001:1002",
        "1003:1004/tcp"
      ],
      "extra_hosts": [
        "bar:8.8.8.8"
      ],
      "tmpfs": [
        "/tmp1"
      ],
      "volumes": [
        {
          "type": "volume",
          "source": "v1",
          "target": "/v1"
        },
        {
          "type": "tmpfs",
          "target": "/tmp2"
        }
      ]
    },
    "s4": {
      "image": "some/image",
      "volumes": [
        "/var/run/docker.sock:/host/run/docker.sock",
        "/run/dbus:/host/run/dbus",
        "/sys:/sys",
        "/proc:/proc",
        "/lib/modules:/lib/modules",
        "/lib/firmware:/lib/firmware",
        "/var/log/journal:/var/log/journal",
        "/run/log/journal:/run/log/journal",
        "/etc/machine-id:/etc/machine-id"
      ]
    }
  }
}
